### PR TITLE
fastapi-update: update to fast-api 0.103.1

### LINKED ISSUE #16: fastapi-featureflags conflicting with fastapi==0.103.1
Tried using featureflags in my pipeline. But failing because of the version.

image

### PR DESCRIPTION
**Pull request by wzharith**
Resolved #16

### CODE REVIEW

**Comment by xmatoha** [comment]
Do we want to remove support for python 3.7? It is and of life as of June 2023.

**Comment by Pytlicek** [comment]
@xmatoha sure! Thanks for this. Please let's try without P. 3.7 🙂

**Comment by Pytlicek** [comment]
@wzharith Thank you very much for your contribution.
@xmatoha Thanks for your work on merging and updating.
🙏 LG2M 👍 Merged.

**Comment by wzharith** [comment]
It's my pleasure, this is my first open source contribution :smile:

**Pull request merged**
